spring:

  # datasource
  datasource:
    url: jdbc:h2:mem:database

  # sql init
  sql:
    init:
      mode: embedded
      schema-locations: classpath:sql/schema.sql

  # h2
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
            StatementCreatorUtils: trace